# .github/workflows/build-gcc-docset.yml
name: Build GCC DocSet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  VERSION: '12.2.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Extract pre-downloaded HTML
      run: |
        mkdir -p gcc-${{ env.VERSION }}/html
        tar -xzf docs/html-archives/gcc-${{ env.VERSION }}-html.tar.gz \
          -C gcc-${{ env.VERSION }}/html

    - name: Install dependencies
      run: npm ci

    - name: Generate DocSet
      run: npm run build:docset

    - name: Zip DocSet
      run: |
        cd output
        zip -r "GCC-${{ env.VERSION }}.docset.zip" "GCC ${{ env.VERSION }}.docset"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gcc-docset-${{ github.ref_name }}
        path: output/GCC-*.docset.zip

